services:
  antrol-generate:
    image: postgres
    container_name: desafio1
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: banco
    ports:
      - 5433:5432
    restart: unless-stopped
